networks:
  internal:
    internal: true
  proxy-stirling-pdf:
    external: true

configs:
  config:
    file: './oauth2-proxy.cfg'

services:
  stirling-pdf:
    container_name: 'stirling-pdf'
    image: 'stirlingtools/stirling-pdf:latest-fat'
    restart: 'unless-stopped'
    networks:
      - 'internal'

  oauth2-proxy:
    image: 'quay.io/oauth2-proxy/oauth2-proxy:latest'
    command: --config /oauth2-proxy.cfg
    restart: 'unless-stopped'
    networks:
      - 'internal'
      - 'proxy-stirling-pdf'
    configs:
      - source: 'config'
        target: '/oauth2-proxy.cfg'
    env_file: '.env'
