networks:
  internal:
    internal: true
  proxy-karakeep:
    external: true

volumes:
  data:
  meilisearch:

services:
  karakeep:
    container_name: 'karakeep'
    image: 'ghcr.io/karakeep-app/karakeep:0.24.1'
    restart: 'unless-stopped'
    networks:
      - 'default'
      - 'internal'
      - 'proxy-karakeep'
    volumes:
      - 'data:/data'
    environment:
      BROWSER_WEB_URL: 'http://chrome:9222'
      MEILI_ADDR: 'http://meilisearch:7700'
      DISABLE_NEW_RELEASE_CHECK: 'true'
      DISABLE_PASSWORD_AUTH: 'true'
      OAUTH_PROVIDER_NAME: 'Pocket ID'
      OAUTH_WELLKNOWN_URL: 'https://auth.home.bojanstipic.com/.well-known/openid-configuration'
      NEXTAUTH_URL: 'https://karakeep.home.bojanstipic.com'
      DATA_DIR: '/data'
    env_file: '.env'

  chrome:
    image: 'gcr.io/zenika-hub/alpine-chrome:123'
    command:
      - '--no-sandbox'
      - '--disable-gpu'
      - '--disable-dev-shm-usage'
      - '--remote-debugging-address=0.0.0.0'
      - '--remote-debugging-port=9222'
      - '--hide-scrollbars'
    restart: 'unless-stopped'
    networks:
      - 'default'

  meilisearch:
    image: 'getmeili/meilisearch:v1.13.3'
    restart: 'unless-stopped'
    networks:
      - 'internal'
    volumes:
      - 'meilisearch:/meili_data'
    environment:
      MEILI_NO_ANALYTICS: 'true'
    env_file: '.env'
