networks:
  internal:
    internal: true
  proxy-excalidraw:
    external: true

configs:
  config:
    file: './oauth2-proxy.cfg'

services:
  excalidraw:
    container_name: 'excalidraw'
    image: 'excalidraw/excalidraw:latest'
    restart: 'unless-stopped'
    networks:
      - 'internal'

  oauth2-proxy:
    image: 'quay.io/oauth2-proxy/oauth2-proxy:latest'
    command: --config /oauth2-proxy.cfg
    restart: 'unless-stopped'
    networks:
      - 'internal'
      - 'proxy-excalidraw'
    configs:
      - source: 'config'
        target: '/oauth2-proxy.cfg'
    env_file: '.env'
